POST http://localhost:4000/api/v1/roles http/1.1
Content-Type: application/json


{
    "name": "test"
}


###
GET http://localhost:4000/api/v1/roles http/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmY4MDAyMWJhODk4NjJmMWI2NTFhNyIsImVtYWlsIjoiZXhhbXBsZWVlQHRlc3QuY29tIiwidXNlcm5hbWUiOiJSb2dlckRvZ2UyIiwiaWF0IjoxNzM2MTM4NjcxLCJleHAiOjE3MzYyMjUwNzF9.h8XjklL598k6-xrCkhTAM6v8oY8SO73xAKrxiNKM860


###
GET http://localhost:4000/api/v1/roles/676f72c265a55cbebfbc2a3d http/1.1



###
PUT  http://localhost:4000/api/v1/roles/676f72c265a55cbebfbc2a3d http/1.1
Content-Type: application/json

{
    "name": "prueba"
}


###
DELETE http://localhost:4000/api/v1/roles/676f72c265a55cbebfbc2a3d http/1.1