POST http://localhost:4000/api/v1/users http/1.1
Content-Type: application/json


{
    "name": "antonio2", 
    "username": "antoniojr2",
    "email": "example2@test.com"
}


###
GET http://localhost:4000/api/v1/users http/1.1


###
GET http://localhost:4000/api/v1/users/676e20fce6fdb94187db8f9b http/1.1



###
PUT  http://localhost:4000/api/v1/users/676e20fce6fdb94187db8f9b http/1.1
Content-Type: application/json


{
    "name": "antonio parrales"
}


###
DELETE http://localhost:4000/api/v1/users/676f7cf39bf6248e4e0073df http/1.1